name: script excution by MothilalNaik
on: 
 push:
  branches: [develop]
  paths: [Template/**]

jobs:
  build:
   runs-on: ubuntu-latest
   environment: Development
   steps:
    - name: echo a string
      run: echo "Hello Mothi! - Developement"
    - name: multiline script
      run: |
        node -v
        npm -v

  scripting:
   needs: build
   runs-on: ubuntu-latest
   environment: Production
   steps:
    - name: echo a string
      run: echo "Hello Mothi! - production"
    - name: multiline script
      run: |
       node -v
       npm -v

