name: Srini Modified File
on:
  workflow_dispatch:
   paths: [Folder_Srini/**]
   inputs:
     environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 
     criter:
        type: choice
        description: 'Name of the employee'
        options:
          - srinu
          - thiru
        required: true
     covi:
        type: choice
        description: 'Name of the 2nd employee'
        options:
          - srinu
          - thiru
          - mothi
        required: false
  pull_request:
    branches:
      - develop/*
jobs:
  build:
   if: ${{ github.event.inputs.environment == 'Development' }}
   runs-on: ubuntu-latest
   steps:
    - name: echo a string for  Environment
      if: ${{ github.event.inputs.criter == 'srinu' }}
      run: echo "Hello Srini! -- Development"
    # - name: multiline script
    #   run: |
    #     node -v
    #     npm -v
  # script:
  #  if: ${{ github.event.inputs.environment == 'Development' }}
  #  runs-on: ubuntu-latest
    - name: echo a string for ${{github.event.inputs.environment}} Environment
      if: ${{ github.event.inputs.covi == 'thiru' }}
      run: echo "Hello Thiru! -- Development"
    - name: multiline script
      run: |
        node -v
        npm -v