name: script excution by srinivas - Continous Integration
on:
  workflow_dispatch:
   paths: [Templates_Two/**]
   inputs:
     environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
     jobs:
        description: 'Which job reuired need to run'
        required: true
        type: boolean
 
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: echo a string for ${{github.event.inputs.environment}} environment
      run: echo "Hello Srini! -- Development"
    - name: multiline script
      run: |
        node -v
        npm -v
  script:
   runs-on: ubuntu-latest
   steps:
    - name: echo a string for ${{github.event.inputs.environment}}environment
      run: echo "Hello Srini! -- Production"
    - name: multiline script
      run: |
        node -v
        npm -v
